name: betachin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'  # Adjusted to match Flutter 3.29.2 (Dart 3.5.x)
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.7.0
  sign_in_with_apple: ^6.1.1
  webview_flutter: ^4.11.0
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  flutter_dotenv: ^5.0.2
  logging: ^1.2.0
  image_picker: ^1.1.2
  universal_html: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true